bvanelli/actualpy

- .github/workflows/test.yaml
- actual/__init__.py
- actual/api.py
- actual/crypto.py
- actual/database.py
- actual/protobuf_models.py
- actual/queries.py
- actual/rules.py
- docker/docker-compose.yml
- requirements-dev.txt
- tests/test_crypto.py
- tests/test_models.py
- tests/test_protobuf.py
- tests/test_rules.py
- Introduce Rule and RuleSet for creating new rules and running existing rules on the local database.
- Refactor some parts of the code to make the API naming more uniform
- Update database model to include the custom reports
Here is one example rule adding with frontend result:
```python
import datetime
from actual import Actual
from actual.queries import create_rule
from actual.rules import (
Action,
Condition,
ConditionType,
Rule,
)
with Actual("http://localhost:5006", password="mypass", file="My Finances") as actual:
action = Action(field="cleared", value=1)
condition = Condition(field="date", op=ConditionType.IS_APPROX, value=datetime.date(2024, 1, 2))
rule = Rule(conditions=[condition], actions=[action], operation="all", stage="pre")
created_rule = create_rule(actual.session, rule) …
```
> Add support for running and inserting rules

- actual/database.py
- actual/queries.py
- actual/rules.py
- actual/schedules.py
- requirements.txt
- tests/test_rules.py
- tests/test_schedules.py
Features:
- Implement schedule support with the bonus of being able to run the rules just as you would normally. The schedule objects can be used to also find the transactions which belong to the schedule, but no support for inserting custom schedules is currently implemented.
Bug fixes:
- Add isapprox for numeric types
- Correctly handle inflow and outflow
- Fix issues where cents could be confused when the data was coming from database
- Rename some of the table attributes from the SQLModel models.
Closes https://github.com/bvanelli/actualpy/issues/13
> feat: Add schedules suppport.

- actual/__init__.py
- actual/api.py
- actual/database.py
- actual/queries.py
- tests/test_database.py
- tests/test_integration.py
Includes the property for balance on the accounts object. Here is the result:
The result of the property:
```python
from actual import Actual
from actual.queries import get_accounts
with Actual("http://localhost:5006", password="mypass", file="My Finances") as actual:
accounts = get_accounts(actual.session)
for acct in accounts:
print(f"Balance for {acct.name} is {acct.balance}")
```
The output from the script:
```
Balance for SimpleFIN Savings is 115524.49
Balance for SimpleFIN Checking is 26134.41
```
Closes #21
> feat: Add balance attribute to account.

- actual/__init__.py
- actual/api/__init__.py
- actual/api/bank_sync.py
- actual/api/models.py
- actual/database.py
- actual/queries.py
- actual/utils/title.py
- codecov.yaml
- tests/conftest.py
- tests/test_bank_sync.py
- tests/test_crypto.py
- tests/test_database.py
- Add reconciliation of transactions using fuzzy matching
- Add pydantic models and endpoint call for the bank sync methods (tested with simplefin)
@latetedemelon @JaxOfDiamonds let me know what you think, I did not have time to test it since it took me way longer than I expected to write it.
I did not have any time to test it so it might be buggy.
I also could not validate the models with the responses from the API from gocardless, that I assume is similar. I'm not sure if they have a dev token just like simplefin has, if you guys know (or can provide an anonimized response) let me know.
Here is one example:
```python
from actual import Actual
with Actual(base_url="http://localhost:5006", password="<your password>", file="<your file>") as actual:
added = actual.run_bank_sync() …
```
> feat: Add bank sync and implement it for the simplefin demo data.

- README.md
- actual/__init__.py
- actual/api/__init__.py
- actual/api/models.py
- tests/test_api.py
- tests/test_integration.py
- Add how to install via pip (closes #14 )
- Small updates to the README documentation, including example on how to generate server backups
- Add option to delete budgets and test for reupload budget, after exporting it
> fix: Add docs for first release

- .github/workflows/try-build.yaml
Checks if module imports are working on the built version, to prevent future importer errors like https://github.com/bvanelli/actualpy/issues/36
Closes https://github.com/bvanelli/actualpy/issues/38
> ci: add job to try and build and import package

- actual/__init__.py
- actual/database.py
- docker/docker-compose.yml
- tests/test_integration.py
Closes https://github.com/bvanelli/actualpy/issues/39
I tested with the missing column, and the model seems to work.
I also added a test to check for missing columns in one of the tests, so that they cannot be missed in the future.
> fix: Correct model for latest actual server.

- actual/api/__init__.py
- actual/api/models.py
- tests/test_api.py
- tests/test_integration.py
Closes https://github.com/bvanelli/actualpy/issues/43
> feat: Support header login as a fallback in case server returns invalid-header

- actual/queries.py
- actual/rules.py
- tests/test_rules.py
Turns out `isbetween` does not share the model with any of the other of the the other entries, but rather implementes the the following data model:
```
{"num1": int1, "num2": int2}
```
This patch files this broken behaviour.
Closes #46
> fix: Fix rules for isbetween that was not validated.

- README.md
Hello!
Firstly, I really appreciate the code you wrote as it saved me a lot of time. 
Just wanted to make a small documentation improvement for actually applying the rules (spend two days debugging, not knowing why it was not actually syncing the changes 😄 )
Thanks!
> docs: Improve rules docs

- actual/rules.py
- tests/test_rules.py
> fix: Change string rules to be case insensitive.

- actual/__init__.py
- actual/database.py
- actual/exceptions.py
- actual/queries.py
- actual/rules.py
- tests/test_rules.py
> feat: Implement custom set split amount rules.

- actual/__init__.py
- actual/database.py
- actual/migrations.py
- actual/version.py
- docker/docker-compose.yml
- tests/test_api.py
- tests/test_integration.py
- Adds reflection when loading the database from Actual. This means that unknown columns will not be supported even when they are not present on the model. This should ensure that migrations will not break as often.
- Possibly dangerous migrations and the method `create_budget` now raise warnings due to the impossibility of running custom Javascript code on the Python wrapper.
- Support for Actual Server 24.9.0
- Reworked the parsing of the JS migrations to account for changes done in Actual 24.9.0
Thanks to @HamedHemati for the contributions on #hackergarten
Closes https://github.com/bvanelli/actualpy/issues/66 
Closes https://github.com/bvanelli/actualpy/issues/58
> feat: Support reflecting models on download.

- actual/queries.py
- actual/rules.py
- tests/test_database.py
- tests/test_rules.py
Implements the `imported_payee` type that was forgotten because it implements the exact same behaviour as string. There must be a reason why this was implemented, but as of now it implements exacly what STRING implements:
https://github.com/actualbudget/actual/blob/bbff543768eda550569c6e0a0a318446fbafaa0e/packages/loot-core/src/shared/rules.ts#L28-L50
Also trimmed the `imported_payee` as the original API does, and set it to the payee if it's missing.
Closes #67
> fix: Cover rules including imported payees.

- actual/__init__.py
- actual/version.py
- tests/test_database.py
- tests/test_integration.py
> fix: Fix issue where reflecting the model would happen before migrations

- actual/__init__.py
- actual/api/__init__.py
- actual/api/bank_sync.py
- actual/api/models.py
- actual/exceptions.py
- tests/test_bank_sync.py
Test it  locally with the Simplefin demo. Here is what happens when the bank sync fails:
```
Traceback (most recent call last):
File "/Users/brunno.vanelli/Documents/git/actualpy/dev/bank_sync.py", line 4, in <module>
added = actual.run_bank_sync()
File "/Users/brunno.vanelli/Documents/git/actualpy/actual/__init__.py", line 490, in run_bank_sync
transactions = self._run_bank_sync_account(acct, default_start_date)
File "/Users/brunno.vanelli/Documents/git/actualpy/actual/__init__.py", line 434, in _run_bank_sync_account
raise ActualBankSyncError(
actual.exceptions.ActualBankSyncError: ('SERVER_DOWN', 'rejected', 'There was an error communciating with SimpleFIN.')
```
Closes #71
> fix: Handle account sync errors when account is not properly setup.

- actual/database.py
- actual/queries.py
- tests/test_database.py
The issue is related to floating-point arithmetic in Python, which affects the accuracy of transaction amount calculations. Specifically, when performing arithmetic operations with floating-point numbers, the results can sometimes be slightly off due to the way floating-point numbers are represented in binary format and when these transactions accumulate, the final account budget result is different from the reality(sometimes by a significant amount). This can lead to incorrect financial tracking and budgeting
For instance, the calculation `-9.95 * 100` results in `-994.9999999999999` instead of the expected `-995` and results in amount of `-9.94` added to ActualBudget instead of `-9.95`.
- [Python decimal module documentation](https://docs.python.org/3/library/decimal.html)
- …
> fix: Floating-Point Representation and Precision Error in transaction amount calculation

- actual/api/__init__.py
- actual/api/models.py
- docker/docker-compose.yml
- tests/test_api.py
- tests/test_bank_sync.py
- tests/test_integration.py
Due to Actual rate limiting, the requests are throttled if coming from "different clients". This means that using the same session for all the requests make them faster.
Here is a benchmark before and after changes, for exporting a bit budget with many changes:
- Before changes: 35.13s
- After changes: 10.90s
This should only affect larger budgets that are remote.
> perf: Improve performance of API queries by using the same session for all

- actual/exceptions.py
- actual/rules.py
- docs/API-reference/exceptions.md
- docs/API-reference/rules.md
- docs/experimental-features.md
Improves and polishes documentation for running rules locally. Includes examples on how to runs rules on newly created transactions, as well as including the rules and exceptions on the documentation.
Closes #68
> docs: Add more documentation on how to work with rules

- actual/__init__.py
- actual/database.py
- tests/test_database.py
Improves the speed when having thousands of entries on the sync backlog by grouping them together. This should make sure that the inserts are done in a single query (INSERT ... ON CONFLICT UPDATE), but should also newly created entities  fields together, making the queries more efficient. Over testing, this helped improve performance of budget with high number of entries high, but also keep the performance of newly created budgets (without many changes) the same. 
Closes #87
> perf: Improve performance of the apply changes method by grouping rows.

- actual/queries.py
- tests/test_database.py
`actualpy` fails to create a transaction without a payee.
When a default (payee='') payee value is used, `actualpy` searches for a payee with an empty name and expects to find _only one_ such payee. Actual Budget uses special payees to represent transfers between accounts. Such payees always have an empty name. If a budget has more than one transfer payee, `create_transaction` will fail because `get_or_create_payee` will find multiple payees with empty names and fail validation.
When a `None` payee value is passed, `create_transaction` succeeds, but then `Actual` errors because of a invalid payee (I haven't captured the exact error, but you can easily reproduce this but calling `create_transaction(..., payee=None)`) and then editing this transaction in Actual.
This proposal adds support …
> Allow creating transactions without payee

- actual/database.py
- actual/queries.py
- tests/test_database.py
Allows you to check the balance for your budget, as well as retrieve the transactions for each budget.
I did try to create transactions directly as a budget property, but that runs into different issues:
- Creating the relationship is quite hard since we have to compare an integer from the budget in the form `202410`, with an integer in the transactions table in the form `20241005`. This makes the "safe" relationship harder to achieve. - When using instead a property, the sqlalchemy session is used instead of the sqlmodel session. It's probably not safe either since we have to convert the result first to the correct models, and I don't know if they would work 100%.
I instead included the budget filter in the `get_transactions` instead.
For example:
```python
...
budget = …
```
> feat: Add budget balance and filter for budget in get_transactions

- .github/workflows/try-build-docs.yaml
Prevents broken documentation links by building docs on PRs.
> ci: Add build docs job to prevent pushing broken docs to main.

- docker/docker-compose.yml
- tests/test_integration.py
I did not find any new features (non experimental) on the frontend, so merging with just tests.
> fix: Run tests on Actual 24.11.0, drop version 24.8.0

- actual/__init__.py
- actual/cli/config.py
- actual/cli/main.py
- actual/database.py
- actual/protobuf_models.py
- actual/queries.py
- tests/test_database.py
- tests/test_integration.py
Allows a performance improvement when working with a local directory. If old files are present, the files will be retrieved only when the sync id has changed. The clock will also be stored on the database and will be used for further requests.
> feat: Use local previously downloaded files when available.

- pyproject.toml
- requirements-dev.txt
- requirements.txt
Details on requests changes  https://github.com/psf/requests/blob/main/HISTORY.md
> Allow newer versions of requests

- actual/api/bank_sync.py
Proposal fix for issue https://github.com/bvanelli/actualpy/issues/99
> fix: Adjust model for Balance.reference_date to be None if not passed (field is optional)

- README.md
- actual/database.py
- actual/queries.py
- docker/docker-compose.yml
- docs/requirements.txt
- mkdocs.yml
- tests/test_database.py
- tests/test_integration.py
Dynamically resolves the type of budget based on the file configuration. There are now two types of budget to choose from, retrieved from the `preferences` table:
- Envelope budgeting (default, recommended): `budgetType` is `rollover`, table is ZeroBudgets
- Tracking budgeting: `budgetType` is `report`, table is `ReflectBudgets`
All budget functions will now respect the globally defined preference when creating/updating budgets.
Closes https://github.com/bvanelli/actualpy/issues/103
> feat: Add support for multiple budget types, introduced in version 25.

- actual/__init__.py
- actual/api/bank_sync.py
- actual/queries.py
- tests/test_bank_sync.py
Allows the accounts to be reconciled when doing the first bank sync. This happens when the expected balance of the account does not match the final balance of the imported transactions, because old transactions are not imported.
This should only affect the first import using the bank sync, or if all transactions are deleted and a new bank sync is done.
Either way, it manages to reproduce 1:1 what we find on the simpleFin demo dataset, when importing from Actual or actualpy.
Closes #29
> feat: Handle balances when using Bank Sync

- actual/database.py
- docs/FAQ.md
- docs/index.md
Improves documentation on many fields, including:
- Explain that bold transactions cannot be achieved via this API
- Add a docstring to most useful database tables
- Document table methods so that they appear on the documentation
- Add one basic example using relationships and properties, using the budget as an example
Closes #105 
Closes #107
> docs: Improve documentation for database objects

- actual/database.py
- actual/queries.py
- actual/rules.py
- tests/conftest.py
- tests/test_database.py
- tests/test_rules.py
Allows assigning a transfer payee to an transaction, that should trigger creating the relative transaction on the other account. This is currently only done using the query, as the validators for both sqlalchemy and pydantic are not fitting for the task.
One of the tests shows how to use it with a rule:
```python
bank = create_account(session, "Bank")
t = create_transaction(session, datetime.date(2024, 1, 1), "Bank", amount=10)
action = Action(field="description", op="set", value=bank.payee.id)
action.run(t)
```
You can also use `actual.queries.set_transaction_payee` directly to set a payee. Calls to `create_transaction` will automatically run this method, but assigning it to a transaction won't trigger anything, unless the method is called directly.
Closes #106
> feat: Support assigning transfer payee

- actual/__init__.py
- actual/api/bank_sync.py
- tests/test_bank_sync.py
Fixes the bank sync optional fields based on the [goCardless documentation](https://developer.gocardless.com/bank-account-data/balance).
Closes #115
> fix: Fix incomplete model for bank sync.

- actual/__init__.py
- actual/api/__init__.py
- actual/api/bank_sync.py
- actual/database.py
- actual/queries.py
- actual/rules.py
- docker/docker-compose.yml
- pyproject.toml
- tests/test_bank_sync.py
- tests/test_cli.py
- tests/test_integration.py
Fixes the incorrect sorting of the Actual transactions since the resolution of https://github.com/actualbudget/actual-server/issues/556
Since the server and frontend code have been moved together, all the bank sync validations are now being done on backend, to allow support for more integrations. This means `actualpy` has to handle less logic when evaluating the bank sync.
This PR solves a couple of issues:
- Correctly calculates the starting balance for goCardless integration
- Correctly sorts the transactions by starting with the "Starting Balance", then consuming all sync transactions in reverse
- Correctly set the sort_order field by multiplying it by 1000 to convert to milliseconds
- Added `Accounts.last_sync` and `Transactions.raw_synced_data`. Nothing has been implemented for them
> Bank sync/correct sorting

- actual/__init__.py
- docs/experimental-features.md
- tests/test_bank_sync.py
Adds an option to run rules after importing the transactions, disabled by default.
Also reported in #68
Closes #30
> feat: Add option to run rules on bank sync.

- actual/__init__.py
- actual/utils/storage.py
- tests/test_api.py
- tests/test_integration.py
When launching the application multiple times, the storage folder is always picked at random if not provided.
The PR makes sure that the uuid will be extracted from the `metadata.json` and then used to create a path that does not require the budget to be redowloaded every time, making the application faster when a storage folder is not provided but the script is called multiple times (i.e. development scenario).
Closes #122
> feat: Make sure the tmp folder is consistent

- actual/api/__init__.py
- actual/database.py
- actual/protobuf_models.py
- actual/queries.py
- actual/utils/conversions.py
- tests/test_api.py
- tests/test_database.py
- tests/test_models.py
Creates functions:
- `get_budgeted_balance`: Returns the budgeted balance as shown by the Actual UI under the category for the individual month. Does not take into account previous months.
- `get_accumulated_budgeted_balance`: Returns the budgeted balance as shown by the Actual UI under the category. This is calculated by summing all considered budget values and subtracting all transactions for them.
Tested performance on my own budget and it looks like budgets are returned in less than 0.02 seconds, so it should be performant enough even with multiple consecutive queries.
> feat: Add query to retrieve the budget balance.

- actual/queries.py
- tests/test_database.py
A few server updates ago (sorry I don't remember when exactly) the `create_transfer` functionality stopped working properly.
When I use the method to create a transfer, the `Payee` field was not set in Actual (it was before IIRC).
After a few experiments and peeking into the sqlite db, I figured, the `payee_id` field must be set on the transaction object.  
This change fixed the bug for me on `v25.6.1`, but I am not sure if it's compatible with older version.
Keen to hear what you think about this.
Thanks!
> fix: Fix a bug where transfer payee was not set
